#future: true

# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "jounileino.com"
description: > # this means to ignore newlines until "email:"
   "Appreciate the past, enjoy the present and implement the future!"

email: "hello@jounileino.com"
#blog logo
logo: "/assets/images/jl-logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/fruhlingsfest.jpg"

name: 'Jouni Leino'
author: 'Jouni Leino'
author_image: "/assets/images/author.jpeg"

paginate:	3

url: "https://jounileino.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@humandebugger'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics: UA-149164081-1

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/humandebugger
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/jounileino
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/jounile
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: linkedin
    url:  https://linkedin.com/in/jounileino
    desc: Connect with me on LinkedIn
    share_url: 
    share_title: 
    share_link:

