# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "jounileino.com"
description: > # this means to ignore newlines until "email:"
   "Appreciate the past, enjoy the present and implement the future!"

email: jouni.leino@siili.com
#blog logo
logo: "/assets/images/author.jpeg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Jouni Leino'
author: 'Jouni Leino'
author_image: "/assets/images/author.jpeg"

paginate:	5

url: "http://profile.jounileino.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@jounile'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/awsfanboy
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/jounileino
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/jounile
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: linkedin
    url:  https://linkedin.com/in/jounileino
    desc: Connect with me on LinkedIn
    share_url: 
    share_title: 
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
